---
- name: "Install default Nginx Web Server"
  hosts: "all"
  become: true
  become_method: sudo

  tasks:
  - name: "Update"
    apt:
      upgrade: "yes"
      update_cache: true
      cache_valid_time: 86400 # One day
    

  - name: "Installing Nginx"
    apt:
      name: "nginx"
      update_cache: true
      state: "latest"
  
  - name: "Starting Nginx and adding it to autostart"
    service:
      name: nginx
      state: started
      enabled: yes
